name: my_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - sphinx 
  - setuptools
  - docutils
  - pydata-sphinx-theme
  - sphinx-copybutton
  - pandoc
  - numpy=2.0.2
  - pandas
  - statsmodels
  - scikit-learn
  - optimask
  - tqdm