name: Run Pytest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest setuptools numpy==1.26.4 numba==0.59.1

    - name: Install timefiller
      run: |
        python setup.py install

    - name: Run Pytest
      run: |
        pytest tests