name: Run Pytest

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.12'
        auto-update-conda: true
        activate-environment: test-env
        use-mamba: true

    - name: Install dependencies with conda
      run: |
        conda install -y pytest setuptools numpy==2.0.2 requests pytables -c conda-forge

    - name: Install timefiller
      run: |
        python setup.py install

    - name: Run Pytest
      run: |
        pytest tests
